version: '3.2'

# volumes:
# data - to hold data
# apps - to hold scripts for the apps
volumes:
  data:
    driver_opts:
      type: none
      device: /Users/tobias/documents/code/docker_test/tshiny_docker/volumes/data
      o: bind
  apps:
    driver_opts:
      type: none
      device: /Users/tobias/documents/code/docker_test/tshiny_docker/volumes/apps
      o: bind

# change ports option below for deployment
services:
  shiny:
    image: shiny-sample-server:latest
    ports:
      - "3838:3838"
      - "80:80"
    volumes:
      - data:/root/data
      - apps:/root/apps
    restart: always
    tty: true
